#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

>&2 echo "NM: $(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/nm-new ${command} --plugin $(${DIR}/config.py GOLD_PLUGIN) $*"
"$(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/nm-new" --plugin "$(${DIR}/config.py GOLD_PLUGIN)" $*
